apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          image: sample-app
          env:
          - name: TEST
            value: TEST
          resources:
            limits:
              memory: 256Mi
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
