apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app
spec:
  tls:
    - secretName: sample-app-cert
      hosts:
        - sample-app.apps.argocd.cc-openshift.de
  rules:
    - host: sample-app.apps.argocd.cc-openshift.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-app
                port:
                  number: 8080
