resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- namespace.yaml
- certificate.yaml

commonLabels:
  app: sample-app

namespace: demo

images:
- name: sample-app
  newName: quay.io/lukeelten/okd-sample-app
  newTag: latest