apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
spec:
  project: default
  source:
    repoURL: 'https://github.com/lukeelten/mastering-gitops-argocd.git'
    path: applications
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
