apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  destination:
    namespace: openshift-monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: monitoring
    repoURL: 'https://github.com/lukeelten/mastering-gitops-argocd.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true