resources:
- install.yaml
- ingress.yaml
- certificate.yaml
- namespace.yaml

namespace: argocd

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-redis
    patch: |-
      - op: remove
        path: /spec/template/spec/securityContext
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
      version: v1
    patch: |-
      - op: add
        path: /data
        value:
          server.insecure: 'true'

commonLabels:
  app: argocd