apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: route53-dns
  namespace: cert-manager
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
      - action:
          - 'route53:GetChange'
        effect: Allow
        resource: 'arn:aws:route53:::change/*'
      - action:
          - 'route53:ChangeResourceRecordSets'
          - 'route53:ListResourceRecordSets'
        effect: Allow
        resource: 'arn:aws:route53:::hostedzone/*'
      - action:
          - 'route53:ListHostedZonesByName'
        effect: Allow
        resource: '*'
  secretRef:
    name: aws-route53-creds
    namespace: cert-manager
  serviceAccountNames:
    - cert-manager
