apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: route53
spec:
  acme:
    email: tobias.derksen@codecentric.de
    privateKeySecretRef:
      name: route53-letsencrypt-secret
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
    - dns01:
        route53:
          region: eu-central-1
          hostedZoneID: Z1FJCCEAIVY91Q